### ISSUE TITLE
стоимость в корзину

### ISSUE THREAD

**Issue by pleaz** [pleaz/kirpich#1]
![2017-02-24_22-41-24 2](https://cloud.githubusercontent.com/assets/2572689/25040336/5d3c18c4-2111-11e7-8fe9-25a24640d8dd.png)

**Comment by RuBik1488** [comment]
Я сделаю

**Comment by pleaz** [comment]
*доставка не добавится отдельной строкой и также в общей сумме при "быстром заказе" и покупке в кредит и добавлении со страницы каталога(при необходимости можно доработать)
*в корзине при изменении количества товара цена доставки не изменится(логичнее убрать это из корзины так как вроде работает не совсем корректно)
*при добавлении нескольких товаров доставка будет дублироваться по каждому товару

**Comment by pleaz** [comment]
ca32edb a8f2fc7
