### ISSUE TITLE
Отображение в firefox

### ISSUE THREAD

**Issue by OTimoshkin** [pleaz/kirpich#24]
Уезжают многие элементы при просмотре сайта через браузер 
![2017-04-24_14-01-11](https://cloud.githubusercontent.com/assets/27953665/25338604/79fd9bd2-2908-11e7-9ea6-b01142874843.png)

**Comment by pleaz** [comment]
и в сафари на опред. разрешении
![dfdf](https://cloud.githubusercontent.com/assets/2572689/25344928/44a6d232-291c-11e7-83ad-2f86bb5b017d.png)
