### ISSUE TITLE
Иконки не были добавлены

### ISSUE THREAD

**Issue by OTimoshkin** [pleaz/kirpich#25]
![2017-04-24_16-17-40](https://cloud.githubusercontent.com/assets/27953665/25339009/e2349740-2909-11e7-8e30-e3427d614acc.png)

**Comment by pleaz** [comment]
@OTimoshkin эта задача уже есть, вот - #9 
 баг поправлен а иконки не заливались сами, так как на основной сайт их все равно перезаливать через админку вручную, можно в админке протестировать что все работает

**Comment by pleaz** [comment]
после переноса правок будут залиты на основной сайт, также все их размеры нужно будет уменьшить предварительно
