### ISSUE TITLE
Не высвечивается запрос о местопложении, не изменяются телефоны при выборе городов

### ISSUE THREAD

**Issue by OTimoshkin** [pleaz/kirpich#26]
![2017-04-24_16-21-38](https://cloud.githubusercontent.com/assets/27953665/25339369/2a3b53fc-290b-11e7-8b31-87a5cdf40416.png)

**Comment by pleaz** [comment]
2a5b881

**Comment by pleaz** [comment]
2a5b881

**Comment by pleaz** [comment]
dfce76b
