### ISSUE TITLE
Не видно реализации добавления транспортных услуг в корзину

### ISSUE THREAD

**Issue by OTimoshkin** [pleaz/kirpich#28]
![2017-04-24_16-36-41](https://cloud.githubusercontent.com/assets/27953665/25339885/b4a5ec04-290c-11e7-97ef-ba6fb14a09c0.png)

**Comment by pleaz** [comment]
вроде разобрались, нужно  еще проверить уходит ли на почту инфа и о доставке вместе с товаром при оформлении заказа
