### ISSUE TITLE
Сделать, чтобы доезжало/открывалось с нужного места в мобильной версии

### ISSUE THREAD

**Issue by OTimoshkin** [pleaz/kirpich#33]
Все разделы в мобильной версии, когда на них переходишь открываются таким образом, что на экране смартфона мы видим каталог, как будто, ничего не изменилось (если до этого, тоже был каталог), т.е. самая верхняя часть страницы открывается.
Нужно, чтобы при нажатии на определенный раздел, страница открывалась с заголовка того раздела, чтобы пользователь понимал эффект от нажатия на данный раздел. Текущая версия работает так, можете там посмотреть. Можете сделать с эффектом "выезжания/спуска вниз", либо просто, сразу открывается страница с нужного места, не знаю, честно говоря, как лучше. На текущей версии выезжает.

**Comment by pleaz** [comment]
<img width="1399" alt="screenshot 2017-05-02 14 34 13" src="https://cloud.githubusercontent.com/assets/2572689/25616373/d835d6fa-2f44-11e7-8459-dabf7e216ccd.png">

**Comment by pleaz** [comment]
2a5b881

**Comment by pleaz** [comment]
59cb534
