### ISSUE TITLE
Убрать точку внизу + область нажатия на галку расширить немного

### ISSUE THREAD

**Issue by OTimoshkin** [pleaz/kirpich#41]
В самой нижней строке стоит точка, нужно чтобы она убиралась.
Также хотел бы попросить, чтобы в мобильной версии область нажатия на галку была увеличена. Т.е. можно визуально оставить все как есть, но когда человек жмет галку с мобильного, большая вероятность, что он несколько раз будет пальцем попадать, пока не попадет.

![screenshot_20170424-221638](https://cloud.githubusercontent.com/assets/27953665/25387611/232ea8c4-29d4-11e7-9885-d847f2af768f.png)

**Comment by pleaz** [comment]
2d6dfb9
